services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp_dev
    ports:
      - '5433:5432' # Port 5433 digunakan untuk menghindari konflik dengan PostgreSQL lokal di port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
