import 'package:flutter_starter_kit/core/di/injection.config.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

/// Global [GetIt] service locator instance.
///
/// Use `getIt<T>()` to retrieve registered dependencies anywhere in the app.
/// All wiring is configured once in [configureDependencies] — called in
/// `main.dart` before `runApp()`.
final GetIt getIt = GetIt.instance;

/// Registers all dependencies into [getIt].
///
/// The [environment] parameter activates environment-specific registrations:
/// - `Environment.dev`  → dev / debug implementations
/// - `Environment.prod` → production implementations
/// - `'staging'`        → staging implementations
///
/// Relies on code generated by `injectable_generator`. Re-run after adding
/// new `@injectable`, `@singleton`, or `@lazySingleton` annotations:
/// ```bash
/// dart run build_runner build --delete-conflicting-outputs
/// ```
@InjectableInit(preferRelativeImports: true)
void configureDependencies(String environment) =>
    getIt.init(environment: environment);
